version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: valenor-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: valenor
    volumes:
      - mongodb_data:/data/db
    networks:
      - valenor-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: valenor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - valenor-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: valenor-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/valenor?authSource=admin
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost:3000
      AI_SERVICE_URL: http://ai-service:8000
    depends_on:
      - mongodb
      - redis
      - ai-service
    networks:
      - valenor-network

  # AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: valenor-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: production
      HOST: 0.0.0.0
      PORT: 8000
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: INFO
    depends_on:
      - redis
    networks:
      - valenor-network

  # Frontend (for development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: valenor-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_AI_SERVICE_URL: http://localhost:8000
    depends_on:
      - backend
      - ai-service
    networks:
      - valenor-network

volumes:
  mongodb_data:
  redis_data:

networks:
  valenor-network:
    driver: bridge
